jobs:
- job: release
  variables:
    imageName: glaux/update-broker-build-deps
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      xenial:
        ubuntuRelease: '16.04'
      bionic:
        ubuntuRelease: '18.04'
  steps:
    - script: sed 's/{{ubuntu_release}}/$(ubuntuRelease)/g' Dockerfile.template > Dockerfile
      displayName: Render Dockerfile
    - script: docker build . -t $(imageName):$(ubuntuRelease)
      displayName: Build image