---
pool:
  vmImage: 'ubuntu-16.04'
variables:
  imageName: glaux/update-broker-build-deps
jobs:
- job: release
  strategy:
    matrix:
      xenial:
        ubuntuVersion: '16.04'
      bionic:
        ubunutVersion: '18.04'
  steps:
    - script: sed 's/{{ubuntu_version}}/$(ubuntuVersion)/g' Dockerfile.template > Dockerfile
      displayName: Render Dockerfile
    - script: docker build . -t $(imageName):$(ubuntuVersion)
      displayName: Build image